global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "distributed_rate_limiter"
    metrics_path: "/metrics"
    scheme: "https"
    static_configs:
      - targets: ["distributed-rate-limiter-35lf.onrender.com:443"]

remote_write:
  - url: "${GRAFANA_PROMETHEUS_URL}"
    basic_auth:
      username: "${GRAFANA_INSTANCE_ID}"
      password: "${GRAFANA_API_TOKEN}"
